import os
import json
import numpy as np
import skimage.draw
import skimage.io
from pycocotools import mask as maskUtils

import cv2

# Third script gets as input a json annotation file generated by the VIA annotation tool,
# and transforms it into another json file in the required format (COCO like)


# Define your paths

##################################################################################################################

##################################################################################################################

############################################################
#  Annotation functions
############################################################

def annToRLE(ann, height, width):
    """
    Convert annotation which can be polygons, uncompressed RLE to RLE.
    :return: binary mask (numpy 2D array)
    """
    segm = ann['segmentation']
    if isinstance(segm, list):
        # polygon -- a single object might consist of multiple parts
        # we merge all parts into one mask rle code
        rles = maskUtils.frPyObjects(segm, height, width)
        rle = maskUtils.merge(rles)
    elif isinstance(segm['leaf_counts'], list):
        # uncompressed RLE
        rle = maskUtils.frPyObjects(segm, height, width)
    else:
        # rle
        rle = ann['segmentation']
    return rle

def extract_bboxes(mask):
    """Compute bounding boxes from masks.
    mask: [height, width, num_instances]. Mask pixels are either 1 or 0.

    Returns: bbox array [num_instances, (y1, x1, y2, x2)].
    """
    boxes = np.zeros([mask.shape[-1], 4], dtype=np.int32)
    for i in range(mask.shape[-1]):
        m = mask[:, :, i]
        # Bounding box.
        horizontal_indicies = np.where(np.any(m, axis=0))[0]
        vertical_indicies = np.where(np.any(m, axis=1))[0]
        if horizontal_indicies.shape[0]:
            x1, x2 = horizontal_indicies[[0, -1]]
            y1, y2 = vertical_indicies[[0, -1]]
            # x2 and y2 should not be part of the box. Increment by 1.
            x2 += 1
            y2 += 1
        else:
            # No mask for this instance. Might happen due to
            # resizing or cropping. Set bbox to zeros
            x1, x2, y1, y2 = 0, 0, 0, 0
        boxes[i] = np.array([y1, x1, y2, x2])
    return boxes.astype(np.int32)


############################################################
#  Dataset
############################################################

class ViaDataset(): #ViaDataset(utils.Dataset)

    def __init__(self, class_map=None):
        self._image_ids = []
        self.image_info = []
        # Background is always the first class
        self.class_info = [{"source": "", "id": 0, "name": "BG"}]
        self.source_class_ids = {}


    def load_data(self, json_decoded):
        """Load a subset of the Balloon dataset.
        DATASET_DIR: Root directory of the dataset.
        subset: Subset to load: train or val
        """
        # Add classes. We have only one class to add.
        self.add_class("fruit", 1, "fruit")

        image_data = json.load(open(input_file_path))
        if "_via_img_metadata" in image_data.keys():
            image_data = image_data["_via_img_metadata"]

        image_data = list(image_data.values())  # don't need the dict keys

        # The VIA tool saves images in the JSON even if they don't have any
        # annotations. Skip unannotated images.

        image_data = [a for a in image_data if a['regions']]
        if json_decoded != None:
            class_name = json_decoded['categories'][0]['name']
            images_original_info = json_decoded['images']
        else:
            class_name = " "
            images_original_info = None
            image_counter = 0

            # Add images
        id = 0
        annotations = []
        data = {}
        data["images"] = []
        missing = []
        for im in image_data:

            im_Name = im['filename']

            if images_original_info != None:
                for image_original_info in images_original_info:
                    if im_Name == image_original_info['file_name']:
                        width = image_original_info['width']
                        height = image_original_info['height']
                        current_image_path = image_original_info['path']
                        current_image_id = image_original_info['id']
                        break
            else:

                img = cv2.imread(os.path.join(images_path, im_Name), 0)
                if img is None:
                    missing.append(im_Name)
                    continue

                print(im_Name)

                height, width = img.shape[:2]
                current_image_path = " "
                current_image_id = image_counter
                image_counter += 1

            current_info = {}
            current_info["file_name"] = im_Name
            current_info["width"] = width
            current_info["height"] = height
            current_info["id"] = current_image_id

            data["images"].append(current_info)


            # Get the x, y coordinaets of points of the polygons that make up
            # the outline of each object instance. There are stores in the
            # shape_attributes

            im_regions= im['regions']
            if type(im_regions) == list:
                regions = {}
                for i in range(len(im_regions)):
                    regions[str(i)]= im_regions[i]
                shapes_dict = [r['shape_attributes'] for r in regions.values()]
            else:
                shapes_dict = [r['shape_attributes'] for r in im['regions'].values()]


            # polygons = [r['shape_attributes'] for r in im['regions'].values()]
            polygons = []
            circles = []
            rects = []
            ellipses = []
            num_of_anns = len(shapes_dict)
            for i in range(num_of_anns):
                if not "name" in shapes_dict[i].keys():
                    a=1
                    continue

                if shapes_dict[i]["name"] == "circle":
                    #circles.append([{"cx":shapes_dict[i]["cx"], "cy":shapes_dict[i]["cy"],"r": shapes_dict[i]["r"]}])
                    circles.append(shapes_dict[i]["cx"])
                    circles.append(shapes_dict[i]["cy"])
                    circles.append(shapes_dict[i]["r"])

                if shapes_dict[i]["name"] == "point":
                    #circles.append([{"cx":shapes_dict[i]["cx"], "cy":shapes_dict[i]["cy"],"r": shapes_dict[i]["r"]}])
                    circles.append(shapes_dict[i]["cx"])
                    circles.append(shapes_dict[i]["cy"])
                    # add radius for visualization
                    shapes_dict[i]["r"] = 10
                    circles.append(shapes_dict[i]["r"])

                if shapes_dict[i]["name"] == "rect":
                    #circles.append([{"cx":shapes_dict[i]["cx"], "cy":shapes_dict[i]["cy"],"r": shapes_dict[i]["r"]}])
                    x = shapes_dict[i]["x"]
                    y = shapes_dict[i]["y"]
                    w = shapes_dict[i]["width"]
                    h = shapes_dict[i]["height"]

                    # fix out of image range annotations
                    if x<0:
                        w=w+x
                        x=0
                    if y<0:
                        h=h+y
                        y=0
                    if (x+w)>width:
                        w=width-x
                    if (y+h)>height:
                        h = height-y

                    rects.append(x)
                    rects.append(y)
                    rects.append(w)
                    rects.append(h)


                if shapes_dict[i]["name"] == "polygon":
                    polygons.append({"all_points_x": shapes_dict[i]["all_points_x"], "all_points_y": shapes_dict[i]["all_points_y"]})

                if shapes_dict[i]["name"] == "ellipse":
                    ellipses.append(shapes_dict[i]["cx"])
                    ellipses.append(shapes_dict[i]["cy"])
                    ellipses.append(shapes_dict[i]["rx"])
                    ellipses.append(shapes_dict[i]["ry"])

                temp = []
                current_ann ={}
                for p in range(len(polygons)):
                    current_poly = polygons[p]

                    temp.append([current_poly['all_points_x'], current_poly['all_points_y']])
                    n = len(current_poly['all_points_x'])
                    ann_reshaped = np.reshape(temp, 2 * n, order='F')
                    new_ann = [ann_reshaped.tolist()]
                    current_ann["segmentation"] = new_ann
                    segAsRLE = annToRLE(current_ann, height, width)
                    current_ann["area"] = float(maskUtils.area(segAsRLE))


            self.add_image(
                class_name,
                image_id=current_image_id,  # use file name as a unique image id
                path=current_image_path,
                width=width, height=height,
                polygons = polygons)

            if len(rects) == 0 and len(circles)>0:
                current_ann = {}
                current_ann["id"] = id
                current_ann["image_id"] = current_image_id
                current_ann["iscrowd"] = 0
                current_ann["category_id"] = 1
                current_ann["circle"] = circles

                annotations.append(current_ann)
                id = id + 1

            j=0
            while j < len(rects):

                if len(polygons) == 0:
                    current_ann = {}

                current_ann["id"] = id
                current_ann["image_id"] = current_image_id
                current_ann["iscrowd"] = 0
                current_ann["category_id"] = 1

                if len(circles)>0:
                    current_ann["circle"] = circles

                current_box = rects[j:j+4]

                current_box = np.asarray(current_box)
                current_box = current_box.tolist()

                # this bbox returns [x, y, w, h]
                current_ann["bbox"] = [current_box[0], current_box[1], current_box[2], current_box[3]]

                current_ann["area"] = float(current_box[2]*current_box[3])

                j+=4
                annotations.append(current_ann)
                id = id + 1

            j = 0
            while j < len(ellipses):
                current_ann = {}
                current_ann["id"] = id
                current_ann["image_id"] = current_image_id
                current_ann["iscrowd"] = 0
                current_ann["category_id"] = 1

                cx, cy, rx, ry = ellipses[j:j + 4]

                # from elipse to bbox
                x = cx - rx
                y = cy - ry
                w = 2 * rx
                h = 2 * ry


                # fix out of image range annotations
                if x < 0:
                    w = w + x
                    x = 0

                if y < 0:
                    h = h + y
                    y = 0

                if (x + w) > width:
                    w = width - x

                if (y + h) > height:
                    h = height - y


                current_box = [x, y, w, h]
                current_box = np.asarray(current_box)
                current_box = current_box.tolist()

                # this bbox returns [x, y, w, h]
                current_ann["bbox"] = [current_box[0], current_box[1], current_box[2], current_box[3]]

                current_ann["area"] = float(current_box[2] * current_box[3])

                j += 4
                annotations.append(current_ann)
                id = id + 1



        print("Missing images:", missing)

        data["annotations"] = annotations


        return data

    def add_class(self, source, class_id, class_name):
        assert "." not in source, "Source name cannot contain a dot"
        # Does the class exist already?
        for info in self.class_info:
            if info['source'] == source and info["id"] == class_id:
                # source.class_id combination already available, skip
                return
        # Add the class
        self.class_info.append({
            "source": source,
            "id": class_id,
            "name": class_name,
        })

    def add_image(self, source, image_id, path, **kwargs):
        image_info = {
            "id": image_id,
            "source": source,
            "path": path,
        }
        image_info.update(kwargs)
        self.image_info.append(image_info)

    def load_mask(self, image_id):
        """Generate instance masks for an image.
       Returns:
        masks: A bool array of shape [height, width, instance count] with
            one mask per instance.
        class_ids: a 1D array of class IDs of the instance masks.
        """

        # Convert polygons to a bitmap mask of shape
        # [height, width, instance_count]
        for image in self.image_info:
            if image['id'] == image_id:
                info = image
        mask = np.zeros([info["height"], info["width"], len(info["polygons"])],
                        dtype=np.uint8)
        for i, p in enumerate(info["polygons"]):
            # Get indexes of pixels inside the polygon and set them to 1
            rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
            mask[rr, cc, i] = 1

        # Return mask, and array of class IDs of each instance. Since we have
        # one class ID only, we return an array of 1s
        return mask, np.ones([mask.shape[-1]], dtype=np.int32)


if __name__ == '__main__':

    # load original annotation file for meta attributes - if exists
    if original_annotations_file_name != None:
        with open(original_annotations_path) as f:
            json_decoded = json.load(f)

        supercategory = json_decoded['categories'][0]['supercategory']
        class_name = json_decoded['categories'][0]['name']
    else:
        json_decoded = None
        supercategory = " "
        class_name = " "


    dataset = ViaDataset()

    data = dataset.load_data(json_decoded)

    annotations = data["annotations"]
    number_of_images = len(dataset.image_info)
    anns_count = 0

    for i in range(number_of_images):
        image_id = dataset.image_info[i]['id']

        # Assuming no segmentation or just one segmentation annotation per image
        mask, class_ids = dataset.load_mask(image_id)

        if not "bbox" in annotations[anns_count].keys():
        #if len(annotations[anns_count]["bbox"])==0:
            if mask.size > 0:
                # Compute Bounding box
                bbox = extract_bboxes(mask)
                numOfBoxes = bbox.shape[0]
                for i in range(numOfBoxes):
                    # this bbox returns [y1,x1,y2,x2], but we need [x1,y1,w,h]
                    current_bbox = bbox[i]
                    new_bbox = [current_bbox[1], current_bbox[0], current_bbox[3] - current_bbox[1],
                                current_bbox[2] - current_bbox[0]]
                    new_bbox = np.asarray(new_bbox)
                    new_bbox = new_bbox.tolist()
                    annotations[anns_count]["bbox"] = new_bbox
                    anns_count = anns_count + 1

        print("Done working on image: ", image_id)

    # Add category data
    cats = {}
    cats["supercategory"] = supercategory
    cats["name"] = class_name
    cats["id"] = 1
    data["categories"] = [cats]


    with open(output_file_path, 'w') as fp:
        json.dump({"categories": data["categories"], "images": data["images"], "annotations": data["annotations"]}, fp)

